### ISSUE TITLE
Waar zijn de schemas?!

### ISSUE THREAD

**Issue by marchelh** [Ideetron/Proximo#1]
De print draagt het open hardware logo, maar draagt niet het open hardware uit. Geen schema's, niet de source code van de app online. Zeer minimale informatie vrijgegeven. Erg jammer allemaal. Lijkt er op dat het weer een nutteloos hardware project is voor publiciteit stunt en dat is zonde van de componenten en energie die daar in is gestopt.

**Comment by GerbendH** [comment]
Beste Marc,

Bedankt voor je vriendelijke vraag. Ik wil je graag attenderen dat alle gegevens van de proximo [hier ](https://github.com/Proximo2018)staan.

De schemas van de laatste versie zijn [hier ](https://github.com/Proximo2018/Proximo/tree/develop/Altium/Project%20Outputs%20for%20Proximo/Proximo_data_v0.9_2018_04_24)te vinden.

Prettige kerstdagen en maak je niet te druk
